# Generated by Django 6.0.1 on 2026-06-11 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='utworzono')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='zaktualizowano')),
                ('name', models.CharField(max_length=200, verbose_name='nazwa czynności')),
                ('description', models.TextField(blank=True, verbose_name='opis tego, co powinno być widoczne')),
                ('recognition_rules', models.TextField(blank=True, verbose_name='warunki rozpoznania')),
                ('exclusion_rules', models.TextField(blank=True, verbose_name='warunki wykluczenia')),
                ('minimum_duration_seconds', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='minimalny czas trwania')),
                ('performed_by', models.CharField(choices=[('operator', 'Operator'), ('machine', 'Maszyna'), ('both', 'Operator i maszyna'), ('unknown', 'Nieokreślone')], default='operator', max_length=20, verbose_name='wykonawca')),
            ],
            options={
                'verbose_name': 'czynność',
                'verbose_name_plural': 'czynności',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('queued', 'W kolejce'), ('running', 'Analiza'), ('completed', 'Zakończono'), ('failed', 'Błąd')], default='queued', max_length=20, verbose_name='status')),
                ('model_name', models.CharField(blank=True, max_length=120, verbose_name='model')),
                ('prompt', models.TextField(blank=True, verbose_name='prompt')),
                ('raw_response', models.TextField(blank=True, verbose_name='surowa odpowiedź')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='start')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='koniec')),
                ('error_message', models.TextField(blank=True, verbose_name='komunikat błędu')),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='szacowany koszt')),
            ],
            options={
                'verbose_name': 'analiza',
                'verbose_name_plural': 'analizy',
                'ordering': ['-started_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='utworzono')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='zaktualizowano')),
                ('name', models.CharField(max_length=200, verbose_name='nazwa operacji')),
                ('code', models.CharField(blank=True, max_length=80, verbose_name='kod operacji')),
                ('description', models.TextField(blank=True, verbose_name='opis operacji')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='kolejność')),
            ],
            options={
                'verbose_name': 'operacja',
                'verbose_name_plural': 'operacje',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='utworzono')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='zaktualizowano')),
                ('name', models.CharField(max_length=200, verbose_name='nazwa procesu')),
                ('code', models.CharField(blank=True, max_length=80, verbose_name='kod procesu')),
                ('description', models.TextField(blank=True, verbose_name='opis procesu')),
            ],
            options={
                'verbose_name': 'proces',
                'verbose_name_plural': 'procesy',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnalysisSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='utworzono')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='zaktualizowano')),
                ('activity_name', models.CharField(max_length=200, verbose_name='nazwa czynności')),
                ('start_seconds', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='od')),
                ('end_seconds', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='do')),
                ('confidence', models.FloatField(default=0.0, verbose_name='pewność')),
                ('reason', models.TextField(blank=True, verbose_name='uzasadnienie')),
                ('is_approved', models.BooleanField(default=False, verbose_name='zatwierdzony')),
                ('activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='processes.activity', verbose_name='czynność')),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='processes.analysis', verbose_name='analiza')),
            ],
            options={
                'verbose_name': 'segment analizy',
                'verbose_name_plural': 'segmenty analizy',
                'ordering': ['start_seconds', 'id'],
            },
        ),
        migrations.AddField(
            model_name='activity',
            name='operation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='processes.operation', verbose_name='operacja'),
        ),
        migrations.AddField(
            model_name='operation',
            name='process',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='processes.process', verbose_name='proces'),
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='videos/%Y/%m/%d/', verbose_name='plik wideo')),
                ('anonymized_file', models.FileField(blank=True, upload_to='anonymized/%Y/%m/%d/', verbose_name='plik po anonimizacji')),
                ('original_filename', models.CharField(max_length=255, verbose_name='oryginalna nazwa pliku')),
                ('duration_seconds', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='czas trwania')),
                ('status', models.CharField(choices=[('uploaded', 'Wgrano'), ('anonymizing', 'Anonimizacja'), ('awaiting_approval', 'Do zatwierdzenia'), ('approved', 'Zatwierdzono'), ('analyzing', 'Analiza'), ('completed', 'Zakończono'), ('failed', 'Błąd')], default='uploaded', max_length=20, verbose_name='status')),
                ('anonymization_error', models.TextField(blank=True, verbose_name='błąd anonimizacji')),
                ('anonymized_at', models.DateTimeField(blank=True, null=True, verbose_name='zanonimizowano')),
                ('approved_for_analysis_at', models.DateTimeField(blank=True, null=True, verbose_name='zatwierdzono do analizy')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='utworzono')),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='processes.operation', verbose_name='operacja')),
            ],
            options={
                'verbose_name': 'wideo',
                'verbose_name_plural': 'wideo',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='analysis',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='processes.video', verbose_name='wideo'),
        ),
    ]
