# Generated by Django 6.0.1 on 2026-06-11 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='cost_is_estimated',
            field=models.BooleanField(default=True, verbose_name='koszt szacowany'),
        ),
        migrations.AddField(
            model_name='analysis',
            name='input_tokens',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='tokeny wejściowe'),
        ),
        migrations.AddField(
            model_name='analysis',
            name='output_tokens',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='tokeny wyjściowe'),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='estimated_cost',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='szacowany koszt (USD)'),
        ),
    ]
