# Generated by Django 6.0.1 on 2026-06-12 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0002_analysis_cost_is_estimated_analysis_input_tokens_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityHint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='utworzono')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='zaktualizowano')),
                ('text', models.TextField(verbose_name='wskazówka')),
                ('is_active', models.BooleanField(default=True, verbose_name='aktywna')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hints', to='processes.activity', verbose_name='czynność')),
                ('confused_with', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confused_hints', to='processes.activity', verbose_name='mylona z')),
                ('source_segment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hints', to='processes.analysissegment', verbose_name='segment źródłowy')),
            ],
            options={
                'verbose_name': 'wskazówka czynności',
                'verbose_name_plural': 'wskazówki czynności',
                'ordering': ['-created_at'],
            },
        ),
    ]
