# Generated by Django 6.0.1 on 2026-06-12 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0003_activityhint'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ['order', 'name'], 'verbose_name': 'czynność', 'verbose_name_plural': 'czynności'},
        ),
        migrations.AddField(
            model_name='activity',
            name='order',
            field=models.PositiveIntegerField(default=1, verbose_name='kolejność'),
        ),
    ]
