# Generated by Django 6.0.1 on 2026-06-12 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0005_backfill_activity_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operation',
            name='code',
        ),
        migrations.RemoveField(
            model_name='process',
            name='code',
        ),
    ]
