# Generated by Django 6.0.1 on 2026-06-12 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0006_remove_operation_code_remove_process_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysissegment',
            name='operation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='segments', to='processes.operation', verbose_name='operacja'),
        ),
        migrations.AddField(
            model_name='analysissegment',
            name='operation_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='nazwa operacji'),
        ),
        migrations.AddField(
            model_name='video',
            name='operations',
            field=models.ManyToManyField(blank=True, related_name='analysis_videos', to='processes.operation', verbose_name='operacje do analizy'),
        ),
        migrations.AddField(
            model_name='video',
            name='process',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='processes.process', verbose_name='proces'),
        ),
        migrations.AlterField(
            model_name='video',
            name='operation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='processes.operation', verbose_name='operacja (pojedyncza, zgodność wsteczna)'),
        ),
    ]
