# Generated by Django 6.0.1 on 2026-06-13 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0009_video_analysis_model_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysissegment',
            name='confidence_unreliable',
            field=models.BooleanField(default=False, verbose_name='pewność niewiarygodna'),
        ),
    ]
