# Generated by Django 6.0.1 on 2026-06-13 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0010_analysissegment_confidence_unreliable'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityhint',
            name='is_positive',
            field=models.BooleanField(default=False, verbose_name='przykład pozytywny'),
        ),
    ]
